### ISSUE TITLE
Podman-compose don't start 

### ISSUE THREAD

**Issue by yodatak** [jdrouet/jolimail#660]
Hi thanks for your awsome work, i use podman compose i i got this error on my computer:

Is you app is different from appmonk ?

podman start -a jolimail_database_1
env: can't execute 'bash': No such file or directory
exit code: 127
podman start -a jolimail_smtp_1
Error: unable to start container 59a47bfbd475abf605b5af734761311aba0a3b688b0d1228127bf6319b731fb6: crun: executable file `node` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
exit code: 125
podman start -a jolimail_jolimail_1
[2023-03-09T03:35:26Z INFO  jolimail] running migrations
thread 'main' panicked at 'couldn't run migration: QueryError("error communicating with the server: failed to lookup address information: Name does not resolve")', src/main.rs:74:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
exit code: 101
podman start -a jolimail_catapulte_1
{"msg":"exec container process (missing dynamic library?) `/usr/bin/catapulte`: No such file or directory","level":"error","time":"2023-03-09T03:35:27.114423Z"}
exit code: 1

**Comment by jdrouet** [comment]
Hey,
Nice to see that you're interested in `jolimail`!

> Is you app is different from appmonk

I don't know `appmonk` 🤷‍♂️ 

> i use podman compose i i got this error on my computer

I'm not supporting podman (and never really used it) so I wouldn't be able to answer you. But if you find a solution to your problem, feel free to open a PR to fix this 😉
