### ISSUE TITLE
Is Catapulte the old name of this project?

### ISSUE THREAD

**Issue by fbartels** [jdrouet/jolimail#77]
In the main readme there is the following:

> Why did we build jolimail?
> Catapulte comes ..

Which then mentions catapulte instead of Jolimail. Looking through the code there are some more mentions of this name.

**Comment by jdrouet** [comment]
Jolimail is the service to design and serves templates whereas [Catapulte](https://github.com/jdrouet/catapulte/) is the microservice that pulls the template from Jolimail, renders it to fit any email client, interpolate variables when it's need and sends the email.
